### ISSUE TITLE
Suggested isIPhoneX function

### ISSUE THREAD

**Issue by jkleroy** [kingj5/iOSKit#11]
Similarly to **isIPad** function, it would be nice to have a **isIPhoneX** function

The following code achieves this
`  

	  Public Function isIPhoneX() as Boolean

	  Declare Function mainScreen Lib UIKitLib selector "mainScreen" (clsRef As ptr) As ptr
  
	  #If Target32Bit
		Return False
	
	  #ElseIf Target64Bit
		Declare Function nativebounds Lib UIKitLib selector "nativeBounds" (obj_id As Ptr) As CGRect64
		Dim sz As CGSize64 = nativeBounds(mainScreen(NSClassFromString("UIScreen"))).rsize
	
		If sz.w = 1125 And sz.h = 2436 Then Return True
	  #EndIf
  
  
  
	End Function

`

**Comment by kingj5** [comment]
If you submit a pull request I will add it in. You can always submit a pull request at any time.

**Comment by jkleroy** [comment]
Finally figured that I had to:
-Uninstall Github desktop
-Install newer version to get an update
-Create a fork of iOSKit, then a Branch and finally a pull request.

**Comment by kingj5** [comment]
Glad you got it figured out, I have merged your pull request
