### ISSUE TITLE
PickerView Default Value

### ISSUE THREAD

**Issue by vdhub** [kingj5/iOSKit#7]
I guess it`s more a feature request than a issue, but is it possible to have same functionality like the Date Picker from the IDE, to be able to load the default value if in case it was provided before. 

Imagine you have the Country list and You already have in the database Italy for example but once you load the popup it will go again to - or to the first record which is quite annoying , so the idea was If the current data is there to show it on the picker as default. 

Thanks again and great work.

**Comment by jkleroy** [comment]
PickerView already has a function SelectedRow(column) = value

Did you try that ?

**Comment by vdhub** [comment]
Well that`s the point , it is not , that one accepts as a input an Integer to give the right value, on DatePicker on Xojo you input the date that you want. 

And why it is not working for me because the data that i get is dynamic , coming from another Software / DB , i just import data and process, so the idea was to scan the entire list, to see which record has that data and then to reference the record no in order to pass the record number integer bu so far no idea how to get that list. 

On Desktop IDE i Extended the Popup menu like 

`Function SelectByText (Extends p As PopupMenu, text As String)
For i As Integer = 0 To p.ListCount - 1
  If p.List(i) = text Then
    p.ListIndex = i
    Return
  End If
Next
`

So it scans for the inputed text , it gets the correct record number and returns the record that has the value. 

We can do same way here ? 

Thanks again.

**Comment by kingj5** [comment]
I'm guessing you are setting the data with an array from your processing? If so you can use indexof on the array you pass in and set that index with 

SelectedRow(column) = mydata.indexof(myvalue)

**Comment by kingj5** [comment]
I believe my previous comment answers the question, so I will close this.  Feel free to reopen or open a new issue if there is still a problem.
